README.md
package.json

A small change to add migration instructions to the readme.

add `yarn migrate` instructions to readme

---

frontend/src/containers/Dashboard.js

This is a bug I noticed when reviewing #59 that happened on the dashboard. If there are no projects in the database then it will error.

Fix bug when projects is empty

---

api/src/index.js

closes #103 
This makes it so swagger docs are served from both `/api` and `/api/docs`.

serve swagger docs from /api and /api/docs

---

api/src/db/knexfile.js

`def` was overriding the `development` config so `production` seeds were being run in development.

fix development knex config

---

components/charts/UserExtentMap.js

When I updated this before, I missed that there were 2 layers in use. This fixes the circle layer so that it renders data from the correct source layer.

Re-enable footprint-point layer

---

api/src/db/migrations/20190205135054_taskers_proxy.js
api/src/services/tm.js
api/src/services/tm_types/tm2.js
api/src/services/tm_types/tm3.js
api/src/tm_clock.js
api/tests/services/tm2.test.js
api/tests/services/tm3.test.js
pages/admin/tasking-managers-add.js
pages/admin/tasking-managers-edit.js

For tasking managers behind firewalls, we can use a proxy URL to host an API. The projects will still use `url`, but the clock process will use `url_proxy`.

Add url proxy to TMs

---

CHANGELOG.md
components/charts/LeafletUserExtentMap.js

OSMesa produces a __sequences__ layer for housekeeping.
react-leaflet-vectorgrid seems to display these even if there is no
style func associated with that layer. We set the style func for the
sequences layer to 0 opacity

Remove MVT artifacts

---

CHANGELOG.md
api/src/models/userCountryEdits.js

This will keep the aggregate country edit count consistent with the OSMESA statistics in the blurb

Leave excluded users' edits in aggregate statistics

---

.gitignore
CHANGELOG.md
README.md
api/src/db/seeds/development/campaigns.js
api/src/db/seeds/development/users.js
api/src/db/seeds/utils.js
api/src/routes/user.js
components/AssignmentsTable.js
components/charts/CampaignsChart.js
components/dashboard/DashboardAssignments.js
lib/utils/getTspanGroups.js
package.json
pages/dashboard.js
pages/user.js
styles/Dashboard.scss

This PR:
- Fixes the seeds so that you don't need to run clocks anymore, `yarn seed` will run both the tm clock and user clock in development and prefill the database with data
- Creates an `allCampaigns` item in the user API response for the dashboard. Campaigns are joined with the osmesa hashtags to produce `allCampaigns` which are campaigns that a user has worked on.
- Displays the allCampaigns in the Campaigns table instead of the concatenation of assignments and favorites.
**Next steps**:
@LanesGood we should design the table for allCampaigns to have a fixed height and be scrollable with more rows. Let me know if you need running this PR

All campaigns in dashboard

---

CHANGELOG.md
api/src/routes/topstats.js

Fixes #369 
✅ Confirmed this was the reason edit totals were different on Home page vs. Users page

Don't count excluded users or their edits in top stats on home page

---

CHANGELOG.md
api/src/services/tm_types/tm2.js
components/campaigns/CampaignCard.js
components/campaigns/CampaignFilters.js
pages/campaign.js

This fixes issue #277.
The new metric is the following mapping to the TM2 and TM3 APIs
For tm2: % mapped is `done + validated`
For tm3: % mapped is `percentMapped`

Close #277

---

CHANGELOG.md
api/src/db/migrations/20190613164216_user_country_changesets.js
api/src/routes/campaign.js
api/src/routes/topstats.js
api/src/services/osmesa.js
components/campaign/CampaignTable.js
package.json
pages/home-component.js

Close #402 
- Changes priority campaign logic
- Language fixes for cards on homepage
- Reverts OSMesa service to using /users (Revert of https://github.com/developmentseed/scoreboard/pull/387/commits/0fad99fe8eca75f3ec02aa824c3eb39b4fd477a9)

Fixes to homepage

---

CHANGELOG.md
components/charts/LeafletCampaignMap.js

I added a requirement of an ID on the GeoJSON data if the feature type is `feature`. If it's MulitPolygon, it seems to work fine with no id

fix/405 Shows AOI on campaign page

---

CHANGELOG.md
styles/App.scss
styles/index.scss

Quick fix to enable map controls on campaign pages, which were previously buried in the z-index stack.

Fixes map controls on campaign pages

---

CHANGELOG.md
lib/utils/format.js

#418 Currently the time util is calculating 'today' any time within 24hrs of the last edit. This appears to the user as bug when the user is viewing the page on the day following the last edit, but 24hrs has not actually passed since the edit time.
My short solution was to change the text from 'today' to 'In the last 24 hours' 
An alternative approach would be to calculate the time from the user edit time and their time zone to figure out when 'today' ends for them.

fix/418 Updates the last edit to reflect current math

---

CHANGELOG.md
components/campaign/CampaignTable.js
styles/Campaigns.scss

Removes redundant tooltips from campaign tables, and add note on Km of roads, railways, coastlines and waterways representing added + modified.

Remove redundant tooltips from campaign tables

---

CHANGELOG.md
components/common/Table.js
lib/i18n/glossary_en.json
styles/Campaigns.scss
styles/index.scss

Closes #454 and fixes path issue for rendering table icons. Also added:
- table header link hover color; allows user to more easily distinguish hovered column
- shortened "POI" description to save space

Update table icons and styling

---

CHANGELOG.md
components/common/Table.js

Catch undefined headers for sort column `title` property. Fixes #462

Catch undefined headers for sort column title

---

components/CSVExport.js
components/campaign/CampaignTable.js

Closes #489 
To test:
- Open any campaign in scoreboard
- Download CSV export from campaign table
- Ensure that totals in export match totals in Campaign Table (noting that the web platform table combines `add`+ `mod`)
- Download CSV export from a user
- Ensure that user download does _not_ include total row

Add total row to Campaign Table CSV export

---

package.json
yarn.lock

Fixes CVE-2019-10757
CVE-2019-10757
high severity
Vulnerable versions: < 0.19.5
Patched version: 0.19.5
knex.js versions before 0.19.5 are vulnerable to SQL Injection attack. Identifiers are escaped incorrectly as part of the MSSQL dialect, allowing attackers to craft a malicious query to the host DB.

Upgrade knex.js to latest.

---

.eslintrc.json
package.json
yarn.lock

this should resolve seeing different behavior in editors vs npm scripts, specifically dynamic imports failing linting in editors.

use babel-eslint as lint parser

---

.env.sample
CHANGELOG.md
README.md
api/src/config.js

- Improve headings and structure of markdown
- Clean up `.env.sample` and add more comments
- Add section to Readme about osm-teams integration
- Add section to Readme about administrator settings
- Remove environment variables from Readme because they were outdated/wrong (.env.sample is the canonical source now)
- Remove apparent crypto seed from api/src/config.js
- Update all secret default values to start with 'changeme!'
Closes #476

Update Readme, default environment vars, and .env.sample.

---

CHANGELOG.md
api/src/routes/teams.js
api/src/services/osmesa.js
api/tests/services/osmesadb.test.js

Relates to #198,  #527 
- Adds an `osmesaStats` data structure to the response in route `/teams:id`
- Does not update `api.yml` because that is a larger task covered by #527 .

Add team statistics to teams route

---

api/src/db/migrations/20200220160412_fix_access_token.js
api/src/models/teams-access-tokens.js
api/src/passport.js
api/src/services/teams.js
components/teams/TeamDetailsForm.js
package.json
yarn.lock

Closes #510 
To test this, 
1. Migrate to the new schema
2. request a new access token, and manually change the value of `expires_at` in the database to make the token expire immediately (for example changing the value of the hours to expiry - 1 hour)
3. Go to `localhost/create-team` and try to create a team
4. the access token should get refreshed in the database with a new `expires_at` time

Fix access token refresh issue

---

pages/teams.js

Fixes #511 
When the component is re-mounted, it does not know of the props
were are already stored in the redux state.
Copying the props in the component constructor fixes it.
This is a workaround, preferred solutions are documented here:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

Fix react state management bug.

---

.env.sample
README.md
api/src/config.js
api/src/services/teams.js

Rough draft to add orgs to scoreboard. This would make Scoreboard work with only 1 organization on osm-teams, and should work for our short-term goals.

Add org id as an environment variable

---

components/dashboard/DashboardBlurb.js

- Adding an `<a>` element suppresses the deprecation warning
`Warning: You're using a string directly inside <Link>. This usage has been deprecated. Please add an <a> tag as child of <Link>`
- Changing the Link's href to a JS variable silences an IDE warning about "file not found".

Fix Next.js deprecation warning; Fix IDE warning.

---

api/src/routes/index.js
api/src/routes/users.js
api/tests/api/users.test.js
components/common/Table.js
lib/i18n/glossary_en.json
lib/store/actions/teams.js
lib/utils/format.js
pages/team.js
pages/teams.js

Teams index page

---

api/src/index.js
api/src/passport.js

Closes #347 by simplifying the session and setting recommended values. I changed setUninitialized to false so that aren't "empty" sessions that are created in case that's where the API was looking for tokens. I also modified the "expires" key to a "maxAge" key (which is recommended).

Fix session timeouts

---

api/src/routes/index.js
api/src/routes/teams.js
api/src/services/teams.js
lib/store/actions/teams.js
pages/edit-moderators.js
pages/edit-team-details.js
server.js

This adds a new page at `teams/:teamId/edit-moderators` that allows the current moderator to modify the moderator list. I added it as a new page because it is interactive rather than being done through a form. We should link to it from either the team edit page, or from the single team page.
This PR is based on `feature/edit-team`, so if we merge that in first we should change the PR target.

Add page for team moderation

---

api/src/routes/teams.js
components/TeamConnectBanner.js
lib/store/index.js
pages/_app.js
pages/teams.js

This propagates the loggedIn prop that is created in `_app.js` for the navbar and header to all pages. Ideally, we would also do this for the authenticated user props and attach it to all page props but that's a larger refactor. 
I've also fixed static links in the banner, and an error that can happen in the state when the user is logged in but there is still no token.

Propagate loggedIn prop to teams page

---

components/teams/TeamCampaignsForm.js
components/teams/TeamMembersForm.js

* Campaigns Pagination bug was calling wrong prop method
* Users Pagination was using the wrong total users and number of
users displayed per page
Closes #570

Fix pagination bug in Teams Edit

---

api/src/routes/teams.js
pages/teams.js

* Root cause seems to be problems transpiling default values in
destructuring objects.  Changing to use Ramda pathOr fixes it.
Fixes #571 
test in a production build and/or on staging server:
`yarn build && yarn start`

Fix filters on teams index page.

---

components/teams/TeamDetailsForm.js

* because the form does not have validation, unique db constraints can be violated.
Relates to #580
This is a workaround. #580 will have to be fixed in a separate PR.

Update label in create team form.

---

api/src/routes/extents.js
package.json
yarn.lock

- res.boom.serverError() was not a function, so use the s3 statuscode and the boom library to
return a more relevant api response.
- upgrade express-boom to get the boomify() function.
- wrap the osmesa.tiles() call with some additional error handling.
Before review:

Fix wrong http error code when s3 fetch of .mvt fails.

---

.gitignore
api/src/db/seeds/development/settings.js
api/src/db/seeds/development/users.js
api/src/routes/campaign.js
api/src/services/tm_types/map_roulette.js
api/src/users_clock.js
api/src/utils/campaignTableSchema.js
api/src/utils/sum_editCounts.js
components/campaign/CampaignBlurb.js
components/campaign/CampaignTable.js
components/common/Table.js
lib/i18n/glossary_en.json
pages/campaign.js
styles/components/_tables.scss

This PR makes attempts at a few things. This is WIP, comments / feedback really needed and appreciated here before I move on.
Some of this has been discussed in slack, will reiterate for clarity.
The goal is to integrate MapRoulette data into scoreboard.
To do this I added a MR class in #589 which loads MR campaigns on `yarn seed`
This PR adds 
- Loading some MapRoulette users on `yarn seed`
- this may be completely unnecessary? im getting closer, but still rather unclear on what data is expected to be available in the deployed env. But this PR pulls in users from MR just as POC, and then tries to extract statistics from OSMesa (fails most of the time because the users are not there).
- Adds conditional method of getting Campaign data
- Prior to this, Scoreboard assumes campaign data from …

Maproulette campaign data

---

README.md

This PR replaces the broken CircleCI badge on the Readme with the equivalent badge from Github Actions.

Add Github CI badge to README.md

---

docker-compose.yml

This is a transient error we noticed occasionally in the local dev environment.
Closes #620

Increase timeout to wait for osmesa mock db to finish loading init.sql

---

api/src/services/tm_types/map_roulette.js
api/tests/services/mr.test.js

Addressing the issue of only pulling in 50 of the oldest maproulette challenges. Unfortunately i don't see a way to determine how many challenges exist through the API, other than requesting until we don't get results. The problem with doing this on seed is that there seem to be roughly 1mil challenges which takes quite a while to download and parse. I don't think it is a good idea to pre-fetch all of these vs maproullette, which requires the user to 'see more' before fetching the next page of results.
As a solution, I have set the scripts to fetch in descending order, sorted by popularity (get most relevant challenges) and increased the cap to 500.
Thoughts?

Add paging loop for maproulette challenges

---

api/src/models/teams-access-tokens.js
api/src/passport.js
api/src/services/teams.js
package.json
yarn.lock

I updated `simple-oauth2` to a new version, which fixes a bug in how refresh tokens are saved [ref issue](https://github.com/lelylan/simple-oauth2/pull/328). This should solve our token refresh woes as it uses a new constructor interface for storing the refresh token.
We should still test this against old tokens on the staging site, and against our current hydra/osm-teams version. We might benefit from also updating hydra on the osm-teams side.

Fix for token refresh

---

components/charts/LeafletCampaignMap.js
pages/campaign.js

This PR:
- Adds osmesa table
- Always includes table title
- Switches MR table names to the appropriate name
- Ensures that Osmesa table is always rendered first on the page, even when MR tables are present
@jvntf I believe this last item is now resolved, but am unable to test on local development given that no MR campaigns have stats in local osmesa campaigns. should we test in the staging environment?

Campaign Table titles + order

---

CHANGELOG.md
api/src/routes/teams.js
api/src/services/teams.js

This fixes the OSM Teams API client library that scoreboard is using because OSM Teams has breaking changes in how permissions work. This closes #676. 
Related: @vgeorge maybe we should release a javascript SDK for OSM Teams that integrations can use?

Fix to OSM teams API lib

---

components/charts/TimeSeriesEditsChart.js
pages/timeseries.js

This PR restricts the Time Series Edits Chart to the top users, sorted by edit, up to 20. The limit of 20 users is somewhat arbitrary, set only by the amount of vertical space available for the legend.

Restrict timeseries chart to top 20 users

---

components/admin/AdminSectionList.js
pages/_app.js
pages/admin/timeseries.js
pages/timeseries.js

This PR:
- Makes `/timeseries` accessible through the Admin panel (please feel free to suggest alternative text - currently "Run Timeseries Analysis")
- Removes link to timeseries from the standard Navbar
- Adds Admin label to timeseries page header

Make timeseries an admin area page
