developmentseed/scoreboard

api/src/db/migrations/20181003140929_custom-badges.js, api/src/routes/badges.js, api/src/routes/index.js, api/tests/badges.test.js
API routes to get, add, delete, and update badges in the custom badges table
=> Custom badge prep

.gitignore, CHANGELOG.md, api/docs/api.yml, api/src/index.js, api/src/knexfile.js, deployment/centos/README.md, deployment/centos/bootstrap.sh, deployment/centos/deploy.sh, deployment/centos/nginx.conf, deployment/centos/scoreboard-api.service, deployment/centos/scoreboard-timer.service, frontend/package.json, frontend/src/components/UserStats.js, frontend/src/components/charts/UserExtentMap.js, frontend/src/index.js, frontend/src/utils/api.js, package.json
This PR makes the version v0.2.1 deployable to our production version of the scoreboard. This is tested on our staging server
=> v0.2.1 release with updated deployment script and small fixes

frontend/src/__tests__/admin-containers.test.js, frontend/src/containers/Admin.js, frontend/src/containers/AdminRoles.js, frontend/src/containers/AdminUserEdit.js, frontend/src/containers/AdminUsers.js, frontend/src/store/index.js
I noticed a bug with user editing where the edit form had the wrong id. This PR fixes that.
=> fix admin user editing

frontend/src/containers/Dashboard.js
=> use BadgeInProgress component on dashboard

README.md, package.json
Update README post next-migration
=> {WIP} Update README.md

pages/index.js
=> fix frontpage stats and graphs

components/CampaignCard.js, pages/campaign.js, pages/index.js, server.js, tests/containers.test.js
=> fix campaign page

components/AllUsersFilter.js
Fixes https://github.com/developmentseed/scoreboard/issues/84
=> Filter out blank country labels and sort

pages/_app.js, styles/App.scss
=> fix login link style

api/bin/commands/create-admin-user.js, api/bin/commands/users/add-role.js, api/src/routes/user.js, pages/admin/badges.js, pages/admin/edit-user.js, pages/edit-user.js
Just a few small fixes that I noticed while checking out the admin section.
=> small fixes for admin cli/ui/api

pages/teams.js
This fixes the linking @scisco
=> Fix team linking on teams page

styles/Badges.scss
=> show in progress badges in color

api/src/routes/users.js
=> make sure null rank shows up last

api/src/routes/users.js, components/AllUsersHeader.js, pages/home-component.js, pages/users.js
=> Close #166

pages/admin/edit-user.js, pages/admin/index.js, pages/admin/users.js
closes #181 
There were just a few instances where we were still using next/router instead of the wrapper module that uses APP_URL_PREFIX.
=> make sure to use wrapper Router.push that uses APP_URL_PREFIX

api/bin/README.md, api/bin/commands/create-admin-user.js, api/bin/scoreboard
closes #207 - now uses dotenv to load the .env file
closes #209 - we could always make a completely new user and make them admin but this simplifies the command and documents it a little better
=> small fixes for the scoreboard cli

pages/_app.js, pages/home-component.js, styles/App.scss, styles/Campaigns.scss, styles/index.scss, styles/settings/variables.scss
These style changes cover Table and Form styles, some basic bar chart improvements, the addition of the card style to the top campaigns on the homepage, and style changes to the navbar. There are many other changes I'd like to make, and some refactoring that I think needs to happen to set us up for responsiveness. 
For now, here's my first PR to the project. Please let me know if I should be adding commit details differently, or if there are other stylistic/process changes I should make when working with the team in GitHub.
=> Design improvements

api/src/fixtures/samplecountry.json, api/src/routes/country.js, api/src/services/osmesa.js, api/tests/api/countries.test.js, components/charts/CountryBlurb.js, pages/country.js
Display country stats in a blurb on the Country page
=> Country stats

CHANGELOG.md, next.config.js, pages/_app.js, styles/App.scss
Closes #311 
Pair coded with @kamicut to update the next config options, which now pull the package.json version number into the footer.
While in the app.scss file, updated ems to rems and made some slight subsequent adjustments
=> Added app version to footer

CHANGELOG.md, components/NotLoggedIn.js, pages/_app.js
Parameterize Editor name when displaying the Not Logged In message
=> Environment variable for "Not Logged In" message

CHANGELOG.md, api/src/db/migrations/20190613164216_user_country_changesets.js, api/src/db/seeds/utils.js, api/src/models/userCountryEdits.js, api/src/services/osmesa.js, api/src/users_clock.js, components/charts/CampaignsChart.js, components/country/CountryUserTable.js, pages/country.js, pages/dashboard.js, pages/user.js
=> Include changeset counts from OSMesa

components/admin/AdminCampaignsSearch.js, components/admin/AdminUsersSearch.js, lib/store/actions/admin.js, lib/store/actions/campaigns.js, lib/store/actions/users.js, lib/store/index.js, lib/utils/fetch-campaigns.js, lib/utils/fetch-users.js
=> Persist search state

package.json
=> Update using audit fix

api/src/db/seeds/development/campaigns.js, api/src/db/seeds/test/campaigns.js, api/src/routes/campaigns.js, api/tests/api/campaigns.test.js, components/campaigns/CampaignFilters.js, lib/store/actions/campaigns.js, lib/utils/fetch-campaigns.js, pages/campaigns.js, styles/index.scss
=> Add archived campaign toggle for campaigns page

CHANGELOG.md, components/CSVExport.js, components/campaign/CampaignTable.js, pages/dashboard.js, pages/user.js, styles/Campaigns.scss, styles/index.scss
Splits `added` and `modified` feature stats into separate columns in the .csv download. Closes #413 
Create CSVExport component for common use in campaign tables, user and dashboard pages. Closes #388
=> CSV Export - split stats and componentize

CHANGELOG.md, api/src/services/osmesa.js
This fixes the defaults for stats for #443
=> Fix defaults for OSMesa stats

api/src/routes/teams.js, components/teams/LocationInput.js, components/teams/TeamDetailsForm.js, lib/store/actions/teams.js, package.json, pages/admin/settings.js, pages/create-team.js, tests/containers.test.js, tests/setup.jest.js, yarn.lock
* Closes #504 
* Adds a create team form page at `scoreboard/create-team`
* Creates a details form that can be reused by edit teams
=> Create Team Page

api/tests/api/favorites.test.js, package.json, yarn.lock
- Upgrades [Ava](https://github.com/avajs/ava) from 1.x to 3.x
- Fixes 1 test regression
=> Upgrade ava to latest

CHANGELOG.md
@guidorice can you confirm whether the changelog addition for Teams Stats page is accurate here?
=> Update changelog with teams page and country sort

components/AssignmentsTable.js, components/dashboard/DashboardAssignments.js
Fixes #540 
- Improve Team Campaigns table.
- Fix campaignlink regression caused by me in da49ceab812d0da8ea32b5f1e3104cf163c1032e.
- Suppress IDE warning re: missing file '/campaigns'
=> Dashboard improvements and fixes.

components/charts/CampaignsChart.js
- Each child in a list should have a unique "key" prop.
Fixes #531
=> Fix React warning

api/src/routes/teams.js, api/src/services/teams.js, components/teams/TeamBlurb.js, lib/utils/teams.js, pages/team.js
=> Team Stats page: empty state, edge cases

api/src/routes/teams.js, api/src/services/teams.js, lib/store/actions/teams.js, lib/store/index.js, pages/dashboard.js, pages/teams.js
=> Add create team button

CHANGELOG.md
@kamicut and @guidorice please add things I've missed for the changelog update, or edit any incorrect additions/fixes.
=> Update Changelog with recent additions

pages/team.js
=> Add scoreboard user country (if exists) to Team detail page.

api/src/routes/teams.js, components/campaign/CampaignTable.js, components/common/Table.js, pages/team.js
=> Fix regression bug

api/tests/services/mr.test.js
=> Fix bad mr test

api/src/tm_clock.js, components/charts/LeafletHomeMap.js
- Exclude map roulette features
- Add click interactivity to link to campaigns
Closes #635 #558 
To test, run `yarn seed` and check the homepage map, maproulette campaigns will be excluded. You can then click on features and they will have a popup linking you to the campaign.
=> Improve home map

api/src/routes/campaign.js, api/src/services/tm_types/map_roulette.js, api/src/utils/campaignTableSchema.js, components/common/Table.js
This PR converts AvgTimeSpent miliseconds to $m $s format in the Panel component and the table.
I'm looking into right-formatting the avgtimespent column, if possible, even though it is now a string.
=> Format MapRoulette avgtimespent

components/charts/BlankStateMap.js, components/charts/LeafletCampaignMap.js, static/map.svg, styles/components/_maps.scss, styles/settings/_variables.scss
Adds blank state map component in case of null map
=> Add blank state map

api/src/db/seeds/development/campaigns.js, api/src/db/seeds/test/campaigns.js, api/src/routes/campaign.js, api/src/services/tm.js, api/src/services/tm_types/index.js, api/src/services/tm_types/tm4.js, api/tests/api/campaigns.test.js, api/tests/services/tm4.test.js, pages/campaign.js
=> Add tm4 interface

api/src/db/seeds/development/settings.js, api/src/routes/index.js, api/src/routes/settings.js, api/src/utils/collapseMetric.js, api/tests/tapes/15f3e25027dbf502ec8a22f6016296cc.js, api/tests/tapes/88d964bc031d938ef54300652b2a5394.js, components/admin/AdminSectionList.js, components/campaigns/CampaignCard.js, components/campaigns/CampaignsListing.js, components/charts/LeafletCampaignMap.js, components/charts/LeafletCountryMap.js, components/charts/LeafletHomeMap.js, components/charts/LeafletUserExtentMap.js, components/charts/ProgressiveExtentMap.js, components/charts/UserExtentMap.js, lib/store/index.js, pages/_app.js, pages/admin/map-settings.js, pages/admin/teams-edit.js, pages/campaign.js, pages/campaigns.js, pages/country.js, pages/dashboard.js, pages/home-component.js, pages/user.js
This PR allows changing the leaflet and WebGL tile source
=> Add new map settings page

api/src/services/tm_types/tm4.js
=> use action=any

Procfile, deployment/centos/scoreboard-timer.service, package.json
=> add clocks_serial
